package com.epam.natasha_mishuk.voucher_comparator.comparator_option;


public enum ExcursionVoucherField {
    VOUCHER_TYPE,VOUCHER_COUNTRY,VOUCHER_TRANSPORT,VOUCHER_ACCOMMODATION,VOUCHER_DAYS,VOUCHER_COST,VOUCHER_EXCURSION_OPTION,VOUCHER_EXCURSION_INSURANCE;
}
